add explicit types to implicit methods and values
twitter/scalding pull request #1660
Opened 2017-03-31 20:24 UTC by fwbrasil

#Problem

The lack of explicit types for implicits makes it harder to follow the scalding code.

#Solution

Add explicit types using [scalafix](https://github.com/scalacenter/scalafix).

2017-03-31 20:27 UTC, fwbrasil commented on scalding-core/src/main/scala/com/twitter/scalding/FieldConversions.scala
>      if (x == '*) {
seems to be github's syntax highlighter having problems to render scala symbols

2017-03-31 20:31 UTC, johnynek requested changes
some narrowing of types requested.

2017-03-31 20:31 UTC, johnynek commented on scalding-commons/src/main/scala/com/twitter/scalding/commons/source/LzoGenericScheme.scala
> +    implicit val baseInj: JavaSerializationInjection[Externalizer[T]] = JavaSerializationInjection[Externalizer[T]]
I think this is really `Injection[Externalizer[T], Array[Byte]]`.

2017-03-31 20:31 UTC, johnynek commented on scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala
> +  implicit def toCumulativeSum[K, U, V](pipe: TypedPipe[(K, (U, V))]): CumulativeSum.CumulativeSumExtension[K, U, V] =
I don't think we need `CumulativeSum.` here.

2017-03-31 20:31 UTC, johnynek commented on scalding-core/src/main/scala/com/twitter/scalding/mathematics/SizeHint.scala
> +  implicit val ordering: SizeHintOrdering.type = SizeHintOrdering
I think this is `Ordering[SizeHint]`

2017-03-31 20:31 UTC, johnynek commented on scalding-core/src/main/scala/com/twitter/scalding/serialization/WrappedSerialization.scala
> +    implicit val initialInj: JavaSerializationInjection[Externalizer[U]] = JavaSerializationInjection[Externalizer[U]]
I think this is `Injection[Externalizer[U], Array[Byte]]`

2017-03-31 20:31 UTC, johnynek commented on scalding-core/src/main/scala/com/twitter/scalding/typed/Sketched.scala
> +  private lazy implicit val cms: com.twitter.algebird.CMSMonoid[Bytes] = CMS.monoid[Bytes](eps, delta, seed)
probably import these.

2017-03-31 20:31 UTC, johnynek commented on scalding-hadoop-test/src/test/scala/com/twitter/scalding/platform/PlatformTest.scala
> +  implicit val stringOrdSer: StringOrderedSerialization = new StringOrderedSerialization()
OrderedSerialization[String]

2017-03-31 20:31 UTC, johnynek commented on scalding-hadoop-test/src/test/scala/com/twitter/scalding/platform/PlatformTest.scala
> +  implicit val stringTup2OrdSer: OrderedSerialization2[String, String] = new OrderedSerialization2(stringOrdSer, stringOrdSer)
`OrderedSerialization[(String, String)]`

2017-04-01 03:19 UTC, johnynek approved these changes

2017-04-01 03:20 UTC, johnynek commented
👍 

Thanks for doing this. Nice to get some experience with this tool.

You might also try running it on algebird.

2017-04-05 01:28 UTC, merged